# Generated by Django 6.0.6 on 2026-07-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdjango', '0002_alter_clientes_fecha_alter_clientes_nombreempleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombreEmpleado',
        ),
        migrations.AddField(
            model_name='clientes',
            name='empleado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appdjango.empleados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
