# Generated by Django 6.0.6 on 2026-07-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombreEmpleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appdjango.empleados'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
